ALTER TABLE family_profile
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键';

ALTER TABLE family_member
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键';

ALTER TABLE member_preference
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键';
