logging:
  level:
    io.yggdrasil.labs.mealmate.*: info
    root: info

spring:
  datasource:
    url: jdbc:h2:mem:mealmate_test;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  flyway:
    enabled: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
